Agent/OLSR set mpr_algorithm_               1    ;# Default (as published in RFC 3626)
Agent/OLSR set routing_algorithm_           1    ;# Default (as published in RFC 3626)
Agent/OLSR set willingness_         	      3    ;# Default (as published in RFC 3626)
Agent/OLSR set tc_ival_                     5    ;# Default (as published in RFC 3626)
Agent/OLSR set hello_ival_            	    2    ;# Default (as published in RFC 3626)
