#!/bin/dash
#Pass a trace file as a parameteer. Ex: ./<Program> <FILE.tr>
FILE="$1"
PACKET_SIZE="$2"
NODE="$3"
FLOW="$4"
if [ -z "$FILE" ]; then
  echo "USAGE: ./Metrics_Performance_Extractor.sh <FILE.tr> <PACKET_SIZE> <NODE_N> <FLOW N>"
  exit 1
fi

if [ -z "$PACKET_SIZE" ]; then
  echo "USAGE: ./Metrics_Performance_Extractor.sh <FILE.tr> <PACKET_SIZE> <NODE_N> <FLOW N>"
  exit 1
fi

if [ -z "$NODE" ]; then
  echo "USAGE: ./Metrics_Performance_Extractor.sh <FILE.tr> <PACKET_SIZE> <NODE_N> <FLOW N>"
  exit 1
fi
if [ -z "$FLOW" ]; then
   echo "USAGE: ./Metrics_Performance_Extractor.sh <FILE.tr> <PACKET_SIZE> <NODE_N> <FLOW N>"
  exit 1
fi
NODE_N=`expr $NODE - 1`
rm -v *.result
rm -v Trace_Cleaned.tr
rm -r Jitter/ 
rm -r Delay/ 
rm -r Forward/ 
rm -r Packet_Loss/
rm -r Throughput/
rm -r Energy/
rm -r PDR/
rm -r Overhead/

#### Clears the trace
echo "Cleanning Trace..."
cat $FILE | sed 's/\[//g' | sed 's/\]//g' | sed 's/\_//g' \
| sed 's/\:/ /g' > Trace_Cleaned.tr
egrep "^[sr].*AGT.*cbr" Trace_Cleaned.tr | awk -F " " '{{if($13=="energy"){print $1 " " $2 " " $3 " " $4 " " $5 " " $6 " " $7 " " $8 " " $9 " " $10 " " $11 " " $12 " " $23 " " $24 " " $25 " " $26 " " $27 " " $28 " " $29 " " $30 " " $31 " " $32} else {print}}}' > Trace_R_S.tr 
echo "Trace Clean and node's number updated..."

######Throughput Calculation ###### 
#Based in: http://ns2ultimate.tumblr.com/post/3442965938/post-processing-ns2-result-using-ns2-trace-ex1 (T. Issaraiyakul and E. Hossain)
echo "Extracting Throughput..."
mkdir -pv Throughput
for conta in $(seq 0 $NODE_N);
do 
cat Trace_R_S.tr | awk -F " " 'BEGIN{ 
lineCount = 0;
totalBits = 0
duration = 0;
}
{if($1=="s" && lineCount==0){ 
	timeBegin = $2; lineCount++
} else {
	timeEnd = $2;
}}
/^r/&&$4=="AGT"&&$14=="'$conta'"{
	if ($8=="'$PACKET_SIZE'") {
		totalBits += $8-20;
   } else {
		totalBits += $8;
   };};
END{
duration = timeEnd-timeBegin;
	if(duration > 0 ) { 
		Thoughput = (totalBits*8)/duration/1e3;
		printf("%3.5f",Thoughput);
	}
};' > Throughput/Throughput_$conta.tr
##### Checks if you have any empty files and writes a value so that the 
# average calculation is computed without errors.
if [ -s Throughput/Throughput_$conta.tr ]; then
awk -F" " '{{if($1!=0.0){{print}}}}' Throughput/Throughput_$conta.tr >> Throughput/mediaV.tr
fi
done;
#Average Throughput
cat Throughput/mediaV.tr | awk '{
Vetor_media[NR] = $0
} END {
	for(j = 1; j <= NR; j++){
		if(j in Vetor_media){	
			soma = soma + Vetor_media[j]	
		}
	}
	media = soma/'$FLOW'
    printf("%3.5f",media)
}' > Throughput/Media_Throughput.tr
#Total Throughput
cat Throughput/mediaV.tr | awk -F " " '{
TV[NR] = $0;
} END {
	for(m = 0; m <= NR; m++){
		soma = soma + TV[m]	
	}
	printf("%3.9f",soma)
}' > Throughput/Total_Throughput.tr
echo "End of Throughput Calculation..."

######Energy Calculation ###### 
echo "Start Energy Calculation..."
mkdir -pv Energy
for conta in $(seq 0 $NODE_N); do
egrep "^[N]" Trace_Cleaned.tr | awk -F" " '{if($5=="'$conta'"){{print $7 }}}' > Energy/Energia_All_by_$conta.e
cat Energy/Energia_All_by_$conta.e | awk 'END{ print 100-$1 }' > Energy/E_Consumption_by_Node_$conta.e
cat Energy/E_Consumption_by_Node_$conta.e >> Energy/Average_Node.e   
done;
cat Energy/Average_Node.e | awk '{
Vetor_media[NR] = $0
} END {
	for(m = 0; m <= NR; m++){
	soma = soma + Vetor_media[m]	
	}
		media = (soma/NR)
		printf("%3.9f",media)
}' > Energy/Energy_Average.tr
echo "End of Energy Calculation..."

#Packet Loss Rate Calculation
echo "Extracting Packet Loss Rate..."
mkdir -pv Packet_Loss
#Print only send (s) events
cat Trace_R_S.tr | awk -F " " '{   
	if($1 == "s" && $4 == "AGT"){
		{print}		
	}
 }' > Packet_Loss/S.tr
#Count just packets sended by application Layer
export s=$(awk -F" " 'END { print NR }' Packet_Loss/S.tr)
#Print only receive (s) events
cat Trace_R_S.tr | awk -F " " '{   
	if($1 == "r" && $4 == "AGT"){
		{print}		
	}
 }' > Packet_Loss/R.tr
#Count just packets received in application Layer
export r=$(awk -F" " 'END { print NR }' Packet_Loss/R.tr)
#Calculates the packet loss rate in units
awk -v S=$s -v R=$r -F " " 'BEGIN {
	PLR = S - R;
	{print PLR}
}' > Packet_Loss/PLR_U.p
#Calculates the packet loss rate as a percentage
awk -v S=$s -v R=$r -F " " 'BEGIN {
	PLR = S - R;
	{print (PLR/S)*100}
}' > Packet_Loss/PLR_R.p
#Record the number of packet generated by application layer
echo $s > Packet_Loss/packet_generated.p
#Record the number of packet received by application layer
echo $r > Packet_Loss/packet_received.p

#Write to a file dropped packets by selfishness.
cat Trace_Cleaned.tr | awk -F " " '{  
	if($5 == "SEL"){  
		{print}
	}		
 }' > Packet_Loss/Selfish_Drops.tr
for No in $(seq 0 $NODE_N);
do 
 cat Packet_Loss/Selfish_Drops.tr | awk -F" " '{
		if($3 == "'$No'"){  
		{print}
		}	
}' > Packet_Loss/Selfish_Drops_$No.tr
awk -F" " 'END { print NR }' Packet_Loss/Selfish_Drops_$No.tr >>  Packet_Loss/Dropped_by_Selfish_Nodes.s
done;	
echo "End Packet Loss Rate Calculation..."

###Routing Overhead Calculation.
echo "Extracting Routing Overhead Rate..."
mkdir -pv Overhead
cat Trace_Cleaned.tr | awk -F" " '{if(($1=="s" || $1=="f") && $4=="RTR" && ($7=="OLSR" || $7=="AODV" || $7=="DSR" || $7=="message")){{print}}}' > Overhead/OVER.tr
awk -F" " 'END { print NR }' Overhead/OVER.tr > Overhead/Overhead.tr 
for conta in $(seq 0 $NODE_N);
do
cat  Overhead/OVER.tr | awk -F" " '{
	if($3=="'$conta'")
	{print}
}' > Overhead/OVER_By_$conta.ov
#Check there is some empty file and writes a value for the average calculus is computed without errors.
if [ ! -s Overhead/OVER_By_$conta.ov ]; then
echo "0" > Overhead/OVER_By_$conta.ov
fi
awk -F" " 'END {if($1=="0") { print NR==0} else { print NR} }' Overhead/OVER_By_$conta.ov >> Overhead/Overhead_by_no.tr
done;
#Another form to calculate routing overhead.
#Calculates routing overhead dividing the byte number of routing overhead by the number of data bytes
export OH=$(cat Overhead/OVER.tr | awk -F " " 'BEGIN {OH = 0;} /^[sf]/&&$4=="RTR"{OH=OH+$8}; END {printf("%.f\n"), OH;}')
export DATA=$(cat Trace_R_S.tr | awk -F " " 'BEGIN {DATA = 0;} /^r/&&$4=="AGT"{DATA=DATA+$8}; END {printf("%.f\n"), DATA;}')
export NOH=$(cat Overhead/Overhead.tr | awk -F" " 'END{ print }')
export NDATA=$(awk -F" " 'END { print NR }' Packet_Loss/R.tr)
echo $OH > Overhead/OH_Bytes.b
echo $DATA > Overhead/DATA_Bytes.b
awk -v overhead=$OH -v data=$DATA -F" " 'BEGIN { print (overhead/data)*100}' > Overhead/Overhead_R.tr
awk -v noverhead=$NOH -v ndata=$NDATA -F" " 'BEGIN { print (noverhead/ndata)*100}' > Overhead/Overhead_Normalized.tr
echo "End Routing Overhead Calculation!!!"

###FORWARD Rate Calculation.
echo "Extracting Forward Rate..."
mkdir -pv Forward
# Create a file with all the Packets Forwarded
cat Trace_Cleaned.tr | egrep "^f.*" | awk -F" " '{if($7=="cbr") {{print}}}'> Forward/FWD_ALL.tr
# Record the quantity of all packets forwarded	
awk -F" " 'END { print NR }' Forward/FWD_ALL.tr > Forward/Forward_ALL_Number.tr
# Record how much each node forward, all packets
for conta in $(seq 0 $NODE_N); do
cat Forward/FWD_ALL.tr | awk -F" " '{
	if($3=="'$conta'") 
	{print}
}' > Forward/FWD_ALL_By_$conta.f
# Checks if there are any empty files and writes a value zero in them
if [ ! -s Forward/FWD_ALL_By_$conta.f ]; then
echo "0" > Forward/FWD_ALL_By_$conta.f
fi
awk -F" " 'END {if($1=="0") {print NR==0} else {print NR}}' \
Forward/FWD_ALL_By_$conta.f >> Forward/Forward_by_no.tr 
done;
# Create a file with all packets forwarded 
cat Forward/FWD_ALL.tr | awk -F" " '{print $3 " " $6 " " $14 " " $16}' > \
Forward/FWD_UNIQ.tr
# Create a file with Packet ID less repetition
cat Forward/FWD_UNIQ.tr | awk -F" " '{{print $2}}' | uniq -u > \
Forward/FWD_UNIQ_PKID.tr
cat Forward/FWD_UNIQ_PKID.tr | awk -F " " 'END{print NR}' > \
Forward/FWD_UNIQ_PKID_Number.tr
# Create a file with all packets received with success, field Packet ID
cat Trace_Cleaned.tr | awk -F" " '{if($1=="r" && $4=="AGT"){{print \
	$6}}}' > Forward/RCV.tr
cat Forward/RCV.tr | awk -F " " '{print}' > Forward/UNIQ_PKID_RCV_F.tr
cat Forward/FWD_UNIQ_PKID.tr | awk -F " " '{print}' >> Forward/UNIQ_PKID_RCV_F.tr	
# Check which packets have been forwarded once
sort -n Forward/UNIQ_PKID_RCV_F.tr | uniq -d > Forward/FWD_Effective.tr 
awk -F" " 'END { print NR}' Forward/FWD_Effective.tr > \
Forward/FWD_Effective_Number.tr 
#Calculates the Packet Forwarding Rate #Calculates the Packet Forwarding Rate 
cat Forward/FWD_UNIQ_PKID_Number.tr > Forward/Forward_TMP_SUCCESS.tr 
cat Forward/FWD_Effective_Number.tr >> Forward/Forward_TMP_SUCCESS.tr 
cat Forward/Forward_TMP_SUCCESS.tr | awk -F " " '{ 
FWD[NR] = $0
} END {	
		SUCCESS = (FWD[2]/FWD[1])*100
		printf("%.f %",SUCCESS)
}' > Forward/Forward_SUCCESS.tr 
echo "End Forward Calculation!!!"

#End-to-End Delay Calculation
echo "Extracting End-to-End Delay..."
mkdir -pv Delay
for conta in $(seq 0 $NODE_N);
do
cat Trace_R_S.tr | awk -F" " '{ 
	if($1 == "s" && $3=="'$conta'" && $4 == "AGT"){
		s_pacote[$6]=$2
		snd[$6]=$6
	}
	if($1 == "r" && $4 == "AGT"){
		r_pacote[$6]=$2
		rcv[$6]=$6
		if($6 in r_pacote && $6 in r_pacote && $6 in snd && $6 in rcv){
			delay=r_pacote[$6]-s_pacote[$6]
			printf("%3.9f\n",delay);
		}
		
	}
}' > Delay/Delay_$conta.tr

#Check if you have some empty file and writes a value for the Delay calculus is computed without errors..
if [ -s Delay/Delay_$conta.tr ]; then
#Average Delay by Node
cat Delay/Delay_$conta.tr |awk -F" " '{
Vetor_media[NR] = $0
} END {
	for(m = 0; m <= NR; m++){
	soma = soma + Vetor_media[m]	
	}
		media = (soma/NR)
		printf("%3.9f",media)

}' > Delay/Media_Delay_$conta.tr
awk -F" " '{print}' Delay/Media_Delay_$conta.tr >> Delay/media.tr
fi
done;
# Global Average Delay
cat Delay/media.tr | awk -F" " '{
Vetor_media[NR] = $0
} END {
	for(m = 0; m <= NR; m++){
	soma = soma + Vetor_media[m]	
	}
		media = (soma/'$FLOW')
		printf("%3.9f",media)
	
}' > Delay/MediaGlobal_At.tr
#Total Delay
cat Delay/media.tr | awk -F " " '{
DL[NR] = $0;
} END {
	for(m = 0; m <= NR; m++){
		soma = soma + DL[m]	
	}
	printf("%3.9f",soma)
}' > Delay/Total_Node_Delay.tr
cat Trace_R_S.tr | awk -F" " 'BEGIN{
count=0;
}
{   
	if($1 == "s" && $4 == "AGT"){
		s_pacote[$6]=$2
		snd[$6]=$6
	}
	if($1 == "r" && $4 == "AGT"){
		count++
		r_pacote[$6]=$2
		rcv[$6]=$6
		if($6 in r_pacote && $6 in r_pacote && $6 in snd && $6 in rcv){
			delay+=r_pacote[$6]-s_pacote[$6]
		}
	}
} END {printf("%3.9f\n",delay/count);}' > Delay/Total_Delay.tr
echo  "End Delay Calculation ..."

# Jitter Calculation
echo "Extracting Jitter..."
mkdir -pv Jitter
for conta in $(seq 0 $NODE_N);
do
cat Delay/Delay_$conta.tr | awk -F " " '{
vetor_Delay[NR] = $0
} END {	
	n = 1
	for(i = 0;i <= NR; i++){
		jitter = vetor_Delay[n] - vetor_Delay[i]
		if(jitter < 0){
			jitter = (jitter * -1)
		}	
		printf("%3.9f\n",jitter)
		n++
	}
}' > Jitter/Jitter_$conta.tr
# Average Jitter
cat Jitter/Jitter_$conta.tr |awk -F" " '{
Vetor_media[NR] = $0
} END {
	for(j = 0; j <= NR; j++){
	soma = soma + Vetor_media[j]	
	}
	
		media = soma/NR
		printf("%3.9f",media)

}' > Jitter/Media_Jitter_$conta.tr
done;
# Global Average Jitter
for conta in $(seq 0 $NODE_N);
do
#Check if you have some empty file and writes a value for the Delay calculus is computed without errors..
if [ -s Delay/Delay_$conta.tr ]; then
awk -F" " '{print}' Jitter/Media_Jitter_$conta.tr >> Jitter/media.tr
fi
done;
cat Jitter/media.tr | awk -F" " '{
Vetor_media[NR] = $0
} END {
	for(m = 0; m <= NR; m++){
	soma = soma + Vetor_media[m]	
	}
		media = soma/'$FLOW'
		printf("%3.9f",media)

}' > Jitter/MediaGlobal_Jt.tr
#Total Jitter
cat Jitter/media.tr | awk -F " " '{
JT[NR] = $0;
} END {
	for(m = 0; m <= NR; m++){
		soma = soma + JT[m]	
	}
	printf("%3.9f",soma)
}' > Jitter/Total_Jitter.tr
#Total Network Jitter
cat Trace_R_S.tr | awk -F" " '{   
	if($1 == "s" && $4 == "AGT"){
		s_pacote[$6]=$2
		snd[$6]=$6
	}
	if($1 == "r" && $4 == "AGT"){
		count++
		r_pacote[$6]=$2
		rcv[$6]=$6
		if($6 in r_pacote && $6 in r_pacote && $6 in snd && $6 in rcv){
			delay=r_pacote[$6]-s_pacote[$6]
			printf("%3.9f\n",delay);
		}
	}
}' > Jitter/Delay_for_Jitter_Network.tr
cat  Jitter/Delay_for_Jitter_Network.tr | awk -F" " '{
count=0;
vetor_EED[NR] = $0;
} END {	
	n = 1
	for(i = 0;i < NR; i++){
		jitter = vetor_EED[n] - vetor_EED[i]
		if(jitter < 0){
			jitter = (jitter * -1)}
		printf("%3.9f\n",jitter)	
		n++ 
		
	} 
}' > Jitter/Total_J.tr
cat Jitter/Total_J.tr | awk -F" " '{
Vetor_media[NR] = $0
} END {
	for(j = 1; j <= NR; j++){
	soma = soma + Vetor_media[j]	
	}
	media = soma/NR
	printf("%3.9f",media)
}' > Jitter/Total_Network_Jitter.tr

echo "End Jitter Calculation..."

#Packet Delivery Rate Calc
echo "Start PDR..."
mkdir -pv PDR
awk -v S=$s -v R=$r -F " " 'BEGIN {
	PDR = (R/S)*100;
	{print PDR}
}' > PDR/PDR.p
echo "Finish PDR..."

#Stores the average of 'n' simulations in a single file.
echo "Extracting Simulation Result ... Please wait"
echo "SIMULATION " >> Simulation_Result.result
echo "Number of Generated Packets:" >> Simulation_Result.result
awk -F" " 'END { print NR }' Packet_Loss/S.tr >> Simulation_Result.result
echo "Total Network Throughput (e.g., Total Bits Delivery/Total Observation Time(s)) (Kbps):" >> Simulation_Result.result
cat Throughput/Total_Throughput.tr >> Simulation_Result.result
echo "\nNodes Average Throughput (e.g., (Node_T1+Node_T2+...+Node_Tn)/Node Flow Number) (Kbps):" >> Simulation_Result.result
cat Throughput/Media_Throughput.tr >> Simulation_Result.result
echo "\nAverage Energy Consumption (e.g., Total Energy Spent/Node Number)(Joules):" >> Simulation_Result.result
cat Energy/Energy_Average.tr >> Simulation_Result.result
echo "\nPacket Loss by Selfishness (Units):" >> Simulation_Result.result
cat Packet_Loss/Dropped_by_Selfish_Nodes.s | awk -F" " '{\
	Vetor_media[NR] = $0
} END {
	for(m = 1; m <= NR; m++){
	soma = soma + Vetor_media[m]	
	}
	printf("%.f",soma)}' >> Simulation_Result.result
echo "\nTotal Packet Loss (Units):" >> Simulation_Result.result
cat Packet_Loss/PLR_U.p >> Simulation_Result.result
echo "Total Packet Loss Percentage (%):" >> Simulation_Result.result
cat Packet_Loss/PLR_R.p >> Simulation_Result.result
echo "Overhead (Units):" >> Simulation_Result.result
cat Overhead/Overhead.tr >> Simulation_Result.result
echo "Overhead_Bytes/Data_Bytes ($OH/$DATA) (%):" >> Simulation_Result.result
cat Overhead/Overhead_R.tr >> Simulation_Result.result
echo "Normalized Overhead (%):" >> Simulation_Result.result
cat Overhead/Overhead_Normalized.tr >> Simulation_Result.result
echo "Forward Percentage (e.g., Total Packet Forward/Packet Received With Success) (%):" >> Simulation_Result.result
cat Forward/Forward_SUCCESS.tr >> Simulation_Result.result
echo "\nTotal Network Delay in seconds (e.g., Total Delay/Packet Received With Success) (s):" >> Simulation_Result.result
cat Delay/Total_Delay.tr >> Simulation_Result.result
echo "Total Delay in seconds (e.g., sum(Node_Delay1+Node_Delay2+...+Node_Delayn)) (s):" >> Simulation_Result.result
cat Delay/Total_Node_Delay.tr >> Simulation_Result.result
echo "\nAverage Delay in seconds (e.g., sum(Node_Delay1+Node_Delay2+...+Node_Delayn)/Node Flow Number)(s):" >> Simulation_Result.result
cat Delay/MediaGlobal_At.tr >> Simulation_Result.result
echo "\nTotal Network Jitter in seconds (e.g., Total Jitter/Packet Received With Success) (s):" >> Simulation_Result.result
cat Jitter/Total_Network_Jitter.tr >> Simulation_Result.result
echo "\nTotal Jitter in seconds (e.g., sum(Node_Jitter1+Node_Jitter2+...+Node_Jittern)) (s):" >> Simulation_Result.result
cat Jitter/Total_Jitter.tr >> Simulation_Result.result
echo "\nAverage Jitter in seconds (e.g., sum(Node_Jitter1+Node_Jitter2+...+Node_Jittern/Node Flow Number)) (s):" >> Simulation_Result.result
cat Jitter/MediaGlobal_Jt.tr >> Simulation_Result.result
echo "\nPDR (%):" >> Simulation_Result.result
cat PDR/PDR.p >> Simulation_Result.result
echo "\n"
echo "\nEND SIMULATION\n\n" >> Simulation_Result.result
cat Simulation_Result.result | sed -e 's/\./\,/' > Resultado_Final.result
dialog \
--title 'WARNING' \
--msgbox 'End of Script!!!' \
6 40
dialog \
--title 'RESULT'  \
--textbox Simulation_Result.result \
0 40
